### ISSUE TITLE
Don't modify files unnecessarily 

### ISSUE THREAD

**Issue by ghost** [BreX900/index_generator#1]
Great package! But there is a problem: generator overwrites index files even when there are no changes. This is noticed by the git, and added to the changes.

![image](https://user-images.githubusercontent.com/25152332/129242485-1a2caaa4-ba83-4e6d-ba30-6df1e6b21c52.png)
![image](https://user-images.githubusercontent.com/25152332/129242714-f4dd5b27-721f-42a5-9a14-5dea646810fc.png)

**Comment by BreX900** [comment]
The problem is that Mac/Linux uses LF instead windows uses CRLF for newline characters
For now, you can set git to always push the same characters until I release a new release
