### ISSUE TITLE
how to add dart:math

### ISSUE THREAD

**Issue by JasCodes** [BreX900/index_generator#3]
Allow to export `import dart:math`

**Comment by BreX900** [comment]
@jascodes Would you like it to be written to the generated file `export 'dart: math';`? Correct?

**Comment by JasCodes** [comment]
Yes.. support for core libraries will be awesome!!

**Comment by JasCodes** [comment]
Hi @BreX900 

The problem still persits. When I try to add for eg. `dart:async` it apprends package in front of it.

Thx

**Comment by SimoneBressan** [comment]
@jascodes Version `3.3.1` released with fix. I also added a test so it can't happen anymore
Sorry for the delay

**Comment by BreX900** [comment]
@jascodes Version `3.3.1` released with fix. I also added a test so it can't happen anymore
Sorry for the delay.

**Comment by BreX900** [comment]
Could you try and close the issue in case everything works fine in the latest version? `3.3.1`

**Comment by JasCodes** [comment]
@BreX900 working wonderfully. Thanks mate!!
